spring.application.name=tutoring-app

# SQLite Datasource Copngifuration (Data Stays Saved)
spring.datasource.url=jdbc:sqlite:tutoring.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Initialization Settings
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:seed.sql

# Disable Hibernate
spring.jpa.hibernate.ddl-auto=none